/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  css: [{
    type: 'autogenerated',
    dirName: 'css'
  }],
  js: [{
    type: 'autogenerated',
    dirName: 'js'
  }],
  diary: [{
    type: 'autogenerated',
    dirName: 'diary'
  }],
  browser: [{
    type: 'autogenerated',
    dirName: 'browser'
  }],
  network: [{
    type: 'autogenerated',
    dirName: 'network'
  }],
  engineering: [{
    type: 'autogenerated',
    dirName: 'engineering'
  }],
  git: [{
    type: 'autogenerated',
    dirName: 'git'
  }],
  ts: [{
    type: 'autogenerated',
    dirName: 'ts'
  }],
  react: [{
    type: 'autogenerated',
    dirName: 'react'
  }],
  vue: [{
    type: 'autogenerated',
    dirName: 'vue'
  }],
};

module.exports = sidebars;