/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  css: [{
    type: 'autogenerated',
    dirName: 'css'
  }],
  js: [{
    type: "category",
    label: "js",
    link: {
      type: "doc",
      id: "js/index"
    },
    collapsible: false,
    items: [{
        type: "category",
        label: "基础",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "js/基础", // '.' 即当前的文档文件夹
        }, ],
      },

      {
        type: "category",
        label: "异步",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "js/异步", // '.' 即当前的文档文件夹
        }, ],
      },
      {
        type: "category",
        label: "数组",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "js/数组", // '.' 即当前的文档文件夹
        }, ],
      },
      {
        type: "category",
        label: "手写",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "js/手写", // '.' 即当前的文档文件夹
        }, ],
      },
      {
        type: "category",
        label: "其他",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "js/其他", // '.' 即当前的文档文件夹
        }, ],
      },
    ]
  }],
  diary: [{
    type: 'autogenerated',
    dirName: 'diary'
  }],

  browser: [{
    type: "category",
    label: "browser",
    link: {
      type: "doc",
      id: "browser/index"
    },
    collapsible: false,
    items: [{
        type: "category",
        label: "浏览器基础",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "browser/浏览器基础", // '.' 即当前的文档文件夹
        }, ],
      },
      {
        type: "category",
        label: "V8工作原理",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "browser/V8工作原理", // '.' 即当前的文档文件夹
        }, ],
      },
      {
        type: "category",
        label: "浏览器安全",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "browser/浏览器安全", // '.' 即当前的文档文件夹
        }, ],
      },
      {
        type: "category",
        label: "浏览器中的页面",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "browser/浏览器中的页面", // '.' 即当前的文档文件夹
        }, ],
      },
      {
        type: "category",
        label: "浏览器中的js运行机制",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "browser/浏览器中的js运行机制", // '.' 即当前的文档文件夹
        }, ],
      },
    ]
  }],
  network: [{
    type: 'autogenerated',
    dirName: 'network'
  }],
  engineering: [{
    type: 'autogenerated',
    dirName: 'engineering'
  }],
  git: [{
    type: 'autogenerated',
    dirName: 'git'
  }],
  ts: [{
    type: 'autogenerated',
    dirName: 'ts'
  }],
  nodejs: [{
    type: 'autogenerated',
    dirName: 'nodejs'
  }],
  react: [{
    type: "category",
    label: "react",
    link: {
      type: "doc",
      id: "react/index"
    },
    collapsible: false,
    items: [{
        type: "category",
        label: "基础",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "react/基础", // '.' 即当前的文档文件夹
        }, ],
      },
      {
        type: "category",
        label: "项目",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "react/项目", // '.' 即当前的文档文件夹
        }, ],
      }, {
        type: "category",
        label: "源码",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "react/源码", // '.' 即当前的文档文件夹
        }, ],
      }, {
        type: "category",
        label: "好文",
        link: {
          type: "generated-index",
        },
        items: [{
          type: "autogenerated",
          dirName: "react/好文", // '.' 即当前的文档文件夹
        }, ],
      }
    ]
  }],
  vue: [{
    type: 'autogenerated',
    dirName: 'vue'
  }],
  designMode: [{
    type: 'autogenerated',
    dirName: 'designMode'
  }],
  algorithm: [{
    type: 'autogenerated',
    dirName: 'algorithm'
  }],
};

module.exports = sidebars;